-- Inserción de las 32 preguntas del test OEJTS
INSERT INTO preguntas (id_pregunta, texto_izquierda, texto_derecha, dimension, peso, orden) VALUES
(1, 'hace listas', 'confía en la memoria', 'JP', 1, 1),
(2, 'escéptico', 'quiere creer', 'FT', -1, 2),
(3, 'aburrido estando solo', 'necesita tiempo solo', 'IE', -1, 3),
(4, 'acepta las cosas como son', 'insatisfecho con cómo son las cosas', 'SN', 1, 4),
(5, 'mantiene un cuarto limpio', 'deja cosas donde sea', 'JP', 1, 5),
(6, 'piensa que "robótico" es un insulto', 'aspira a tener una mente mecánica', 'FT', 1, 6),
(7, 'energético', 'tranquilo', 'IE', -1, 7),
(8, 'prefiere examen de opción múltiple', 'prefiere respuestas de ensayo', 'SN', 1, 8),
(9, 'caótico', 'organizado', 'JP', -1, 9),
(10, 'se lastima fácilmente', 'piel gruesa', 'FT', 1, 10),
(11, 'trabaja mejor en grupos', 'trabaja mejor solo', 'IE', -1, 11),
(12, 'enfocado en el presente', 'enfocado en el futuro', 'SN', 1, 12),
(13, 'planea con mucha anticipación', 'planea a último minuto', 'JP', 1, 13),
(14, 'quiere el respeto de la gente', 'quiere su amor', 'FT', -1, 14),
(15, 'se agota en fiestas', 'se energiza en fiestas', 'IE', 1, 15),
(16, 'encaja', 'sobresale', 'SN', 1, 16),
(17, 'mantiene opciones abiertas', 'se compromete', 'JP', -1, 17),
(18, 'quiere ser bueno arreglando cosas', 'quiere ser bueno arreglando personas', 'FT', -1, 18),
(19, 'habla más', 'escucha más', 'IE', -1, 19),
(20, 'al describir un evento, dice qué pasó', 'al describir un evento, dice qué significó', 'SN', 1, 20),
(21, 'hace el trabajo de inmediato', 'procrastina', 'JP', 1, 21),
(22, 'sigue el corazón', 'sigue la cabeza', 'FT', 1, 22),
(23, 'se queda en casa', 'sale a la ciudad', 'IE', 1, 23),
(24, 'quiere la visión general', 'quiere los detalles', 'SN', -1, 24),
(25, 'improvisa', 'prepara', 'JP', -1, 25),
(26, 'basa la moralidad en la justicia', 'basa la moralidad en la compasión', 'FT', -1, 26),
(27, 'le cuesta gritar muy fuerte', 'gritar a otros cuando están lejos viene naturalmente', 'IE', 1, 27),
(28, 'teórico', 'empírico', 'SN', -1, 28),
(29, 'trabaja duro', 'juega duro', 'JP', 1, 29),
(30, 'incómodo con las emociones', 'valora las emociones', 'FT', -1, 30),
(31, 'le gusta actuar frente a otras personas', 'evita hablar en público', 'IE', -1, 31),
(32, 'le gusta saber "quién", "qué", "cuándo"', 'le gusta saber "por qué"', 'SN', 1, 32);
