-- Inserción de los 16 tipos de personalidad MBTI
INSERT INTO tipos_personalidad (codigo, nombre, descripcion_corta, descripcion_completa, fortalezas, debilidades, carreras_sugeridas, famosos_tipo, porcentaje_poblacion) VALUES
('INTJ', 'El Arquitecto', 'Estratega imaginativo con un plan para todo', 'Los INTJ son pensadores estratégicos que destacan por su capacidad de planificación a largo plazo. Confían en su intuición y razonamiento lógico para resolver problemas complejos.', 'Pensamiento estratégico, independencia, determinación, creatividad', 'Arrogancia, dificultad para expresar emociones, excesivamente críticos', 'Científico, ingeniero, estratega empresarial, programador', 'Elon Musk, Isaac Newton, Friedrich Nietzsche', 2.1),

('INTP', 'El Lógico', 'Innovador filosófico, sediento de conocimiento', 'Los INTP son pensadores analíticos que aman las teorías abstractas y disfrutan explorando ideas complejas. Son innovadores naturales.', 'Pensamiento lógico, creatividad, objetividad, curiosidad intelectual', 'Insensibilidad, distracción, dificultad para seguir reglas', 'Científico, filósofo, matemático, arquitecto de software', 'Albert Einstein, Charles Darwin, Bill Gates', 3.3),

('ENTJ', 'El Comandante', 'Líder audaz, imaginativo y de voluntad fuerte', 'Los ENTJ son líderes naturales que destacan en organizar personas y proyectos. Son decididos y orientados a objetivos.', 'Liderazgo natural, eficiencia, confianza, visión estratégica', 'Intolerancia, impaciencia, arrogancia, dominantes', 'CEO, director ejecutivo, abogado, consultor estratégico', 'Steve Jobs, Margaret Thatcher, Napoleon Bonaparte', 1.8),

('ENTP', 'El Innovador', 'Pensador inteligente y curioso que no puede resistir un desafío intelectual', 'Los ENTP son innovadores creativos que aman debatir y explorar nuevas ideas. Cuestionan todo y disfrutan de desafíos intelectuales.', 'Ingenio, originalidad, carisma, conocimiento amplio', 'Argumentativos, insensibles, intolerantes con rutinas', 'Emprendedor, inventor, abogado, científico', 'Thomas Edison, Leonardo da Vinci, Mark Twain', 3.2),

('INFJ', 'El Abogado', 'Idealista silencioso pero inspirador', 'Los INFJ son idealistas con profunda comprensión de las personas. Buscan significado y conexión en todo lo que hacen.', 'Empatía, visión, creatividad, determinación', 'Perfeccionismo, sensibilidad excesiva, privacidad extrema', 'Consejero, psicólogo, escritor, trabajador social', 'Mahatma Gandhi, Martin Luther King Jr., Nelson Mandela', 1.5),

('INFP', 'El Mediador', 'Idealista poético, amable y altruista', 'Los INFP son soñadores guiados por valores profundos. Son creativos, compasivos y buscan autenticidad en todo.', 'Idealismo, empatía, creatividad, lealtad', 'Demasiado idealistas, difíciles de conocer, autocrít', 'Escritor, artista, psicólogo, maestro', 'William Shakespeare, J.R.R. Tolkien, Vincent van Gogh', 4.4),

('ENFJ', 'El Protagonista', 'Líder carismático e inspirador capaz de cautivar a su audiencia', 'Los ENFJ son líderes naturales muy carismáticos e inspiradores. Se preocupan genuinamente por los demás y motivan a las personas.', 'Carisma, altruismo, liderazgo natural, empatía', 'Demasiado idealistas, demasiado desinteresados, sensibles a las críticas', 'Maestro, consejero, coach de vida, político', 'Barack Obama, Oprah Winfrey, Martin Luther King Jr.', 2.5),

('ENFP', 'El Activista', 'Espíritu libre entusiasta, creativo y sociable', 'Los ENFP son personas energéticas y creativas que ven la vida llena de posibilidades. Son entusiastas, espontáneos y genuinos.', 'Entusiasmo, creatividad, sociabilidad, optimismo', 'Desorganizados, dificultad para enfocarse, hipersensibles', 'Artista, consejero, emprendedor, maestro', 'Robin Williams, Ellen DeGeneres, Walt Disney', 8.1),

('ISTJ', 'El Logista', 'Individuo práctico y enfocado en los hechos, cuya confiabilidad es incuestionable', 'Los ISTJ son trabajadores confiables y responsables que valoran la tradición y el orden. Son prácticos y orientados a los detalles.', 'Responsabilidad, practicidad, orden, lealtad', 'Terquedad, insensibilidad, resistencia al cambio', 'Contador, auditor, administrador, ingeniero', 'George Washington, Queen Elizabeth II, Warren Buffett', 11.6),

('ISFJ', 'El Defensor', 'Protector dedicado, dispuesto a defender a sus seres queridos', 'Los ISFJ son personas cálidas y consideradas que se dedican a cuidar a los demás. Son leales, pacientes y confiables.', 'Lealtad, paciencia, practicidad, dedicación', 'Demasiado humildes, reprimen sus sentimientos, resistentes al cambio', 'Enfermero, maestro, trabajador social, administrador', 'Mother Teresa, Queen Elizabeth II, Rosa Parks', 13.8),

('ESTJ', 'El Ejecutivo', 'Excelente administrador incomparable en gestionar cosas y personas', 'Los ESTJ son organizadores naturales que valoran la tradición, el orden y la seguridad. Son directos, honestos y dedicados.', 'Organización, dedicación, honestidad, lealtad', 'Inflexibilidad, dificultad con emociones, juicio severo', 'Gerente, oficial militar, juez, ejecutivo', 'Judge Judy, Lyndon B. Johnson, John D. Rockefeller', 8.7),

('ESFJ', 'El Cónsul', 'Personas extraordinariamente cariñosas, sociables y populares', 'Los ESFJ son personas orientadas a ayudar a los demás que disfrutan de la armonía social. Son cálidos, cooperativos y responsables.', 'Lealtad, sensibilidad, calidez, altruismo', 'Preocupados por su estatus social, inflexibles, necesitan aprobación', 'Maestro, enfermero, asistente social, recepcionista', 'Bill Clinton, Taylor Swift, Sally Field', 12.3),

('ISTP', 'El Virtuoso', 'Experimentador audaz y práctico, maestro de todo tipo de herramientas', 'Los ISTP son solucionadores de problemas prácticos que disfrutan explorando cómo funcionan las cosas. Son espontáneos y adaptables.', 'Optimismo, creatividad, espontaneidad, racionalidad', 'Terquedad, insensibilidad, aversión al compromiso', 'Mecánico, piloto, ingeniero, detective', 'Clint Eastwood, Michael Jordan, Bear Grylls', 5.4),

('ISFP', 'El Aventurero', 'Artista flexible y encantador, siempre dispuesto a explorar y experimentar', 'Los ISFP son personas creativas y sensibles que viven en el momento. Son artísticos, apasionados y valoran la libertad.', 'Sensibilidad, imaginación, pasión, curiosidad', 'Demasiado sensibles, difíciles de conocer, impredecibles', 'Artista, diseñador, músico, chef', 'Michael Jackson, Marilyn Monroe, Mozart', 8.8),

('ESTP', 'El Emprendedor', 'Personas inteligentes, enérgicas y muy perceptivas que disfrutan el riesgo', 'Los ESTP son personas energéticas que viven al máximo y disfrutan de la acción. Son pragmáticos, directos y espontáneos.', 'Audacia, racionalidad, sociabilidad, percepción', 'Impacientes, intolerantes, asumir riesgos, insensibles', 'Emprendedor, agente de ventas, detective, paramédico', 'Donald Trump, Ernest Hemingway, Madonna', 4.3),

('ESFP', 'El Animador', 'Artistas espontáneos, enérgicos y entusiastas que nunca aburrirán a su audiencia', 'Los ESFP son personas orientadas a disfrutar la vida que aman estar rodeadas de gente. Son espontáneos, energéticos y divertidos.', 'Audacia, estética, sociabilidad, practicidad', 'Sensibles, evitan conflictos, se aburren fácilmente, dificulta para planificar', 'Animador, actor, artista, diseñador de eventos', 'Elvis Presley, Marilyn Monroe, Jamie Oliver', 8.5);
